/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface NpmApiCache {
  cache_date: string;
  id: Generated<number | null>;
  response: string;
  url: string;
}

export interface Snapshots {
  downloads: string;
  id: Generated<number | null>;
  package_id: number;
  snapshot_date: string;
}

export interface TrackedPackages {
  created_at: Generated<string>;
  id: Generated<number | null>;
  package_name: string;
}

export interface UserTrackedPackages {
  package_id: number;
  user_id: string;
}

export interface DB {
  npm_api_cache: NpmApiCache;
  snapshots: Snapshots;
  tracked_packages: TrackedPackages;
  user_tracked_packages: UserTrackedPackages;
}
