import { randomBytes } from 'node:crypto';
import { existsSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const outputPath = resolve(process.cwd(), '.github-app.local.env');
const force = process.argv.includes('--force');

if (existsSync(outputPath) && !force) {
  console.error(
    `.github-app.local.env already exists at ${outputPath}. Re-run with --force to overwrite it.`
  );
  process.exit(1);
}

const encryptionKey = randomBytes(32).toString('hex');
const webhookSecret = randomBytes(32).toString('hex');

const contents = `# Generated by tools/generate-github-secrets.ts
# Copy these values into:
# - apps/npm-burst/.env.local
# - apps/cronjob/.dev.vars (ENCRYPTION_KEY only)
# - Cloudflare secrets for deployed environments

ENCRYPTION_KEY=${encryptionKey}
GITHUB_WEBHOOK_SECRET=${webhookSecret}
`;

writeFileSync(outputPath, contents, 'utf8');

console.log(`Wrote GitHub app secrets to ${outputPath}`);
console.log('Copy ENCRYPTION_KEY into both app and cron env files.');
console.log('Copy GITHUB_WEBHOOK_SECRET into the app env file and GitHub App webhook settings.');
