name: "Combine PRs"

# Controls when the action will run - in this case triggered manually
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules, !node_modules/.*
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install

      - name: Test / Lint / Build
        run: |
          npx nx affected -t test lint build
      
      - name: E2E
        run: |
          npx nx affected -t e2e

      - name: Deploy
        if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx nx deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
