name: 'CI / CD'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

# Controls when the action will run - in this case triggered manually
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ci:
    name: Nx Cloud - Main Job (format / lint / test / build)
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.8
    with:
      main-branch-name: 'main'
      parallel-commands: |
        npx nx-cloud record npx nx format:check
      parallel-commands-on-agents: |
        yarn nx affected -t lint test build --parallel 3

  e2e:
    name: E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules, !node_modules/.*
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install

      - name: 'Cypress'
        run: |
          npx nx affected -t e2e --record
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_CLOUD_KEY}}

  ci-agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.8
    with:
      number-of-agents: 3

  deploy:
    name: 'Deploy'
    needs:
      - 'ci'
      - 'e2e'
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: main

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules, !node_modules/.*
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install

      - name: Deploy
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx nx deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
