name: "Combine PRs"

# Controls when the action will run - in this case triggered manually
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "combine-prs"
  deploy-to-gh-pages:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules, !node_modules/.*
          key: ${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: |
          npm install

      - name: Test / Lint / Build
        run: |
          npx nx affected -t lint build

      - name: Deploy
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npx nx deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
